### ISSUE TITLE
Dependencies to git repositories

### ISSUE THREAD

**Issue by mtangemann** [mtangemann/r3#1]
It should be possible to specify dependencies to git repositories. E.g., using dependency types:

```yaml
dependencies:
- type: git
  origin: git@github.com:mtangemann/r3.git
  commit: a824b98dd8ec414443baad0a827191c727ad35aa
```
